### ISSUE TITLE
Zome for Jai Thep

### ISSUE THREAD

**Issue by zuperninja** [zuperninja/zuperninja.github.io#1]
### SketchUp 2016
1. Télécharger et installer Sketch Up 2016 : https://www.sketchup.com/fr/download/all
1. Télécharger plugin : https://github.com/surikat/zome-polar-rhombizonahedron
**Dans sketchup : ** 
1. Barre de menu > window > preference > extension > install extension > cherche le fichier extrait en .rbz
1. Redémarrer sketch up
1. Barre de menu > extension > zome > choisir configuration voulue et PAF !

### SketchUp 2017
1. Télécharger et installer Sketch Up 2017 : https://www.sketchup.com/fr/download/all
1. Télécharger plugin : https://github.com/surikat/zome-polar-rhombizonahedron
**Dans sketchup : ** 
1. Barre de menu > window > extension manager > install extension > cherche le fichier extrait en .rbz
1. Redémarrer sketch up
1. Barre de menu > extension > zome > choisir configuration voulue et PAF !

**Comment by zuperninja** [comment]
[Théorie](http://archilibre.org/ateliers/zome/zome.html) sur la construction du zome

**Comment by zuperninja** [comment]
Theme : Atlantis, giant form under the sea.
Color : light and clear / blue, green, silver

Shades made of tye-die that looks like seaweed or water
Jellyfish and creature with plastic bottle and some LED in it


STAGE : 

The top of the head from an ancient giant. Only the eyes and hat are coming out of the ground. The DJ is the brain of the giant.


Eyes made in blue resin with indirect light. Servo motor to make them blink when people approach.
Fur for the eyebrow and some paint to make some realistic appereance (glued)
Top of the ears with wire and papier maché painted with earth colors. And some dirt glued to it to make it looks like stone/mineral.
Eyelashes with pipe cleaner ? Glitter, silver, green, black ?

**Comment by zuperninja** [comment]
Materials for the eye : 

x2 Big round plastic bowl
x1 Mold release spray
Resin
Aquamarine glitter (very light)
Nail Polish (green and light blue)
Spatula
Mixing bowl

**Comment by zuperninja** [comment]
EYE : 

Papier maché x2
Box x2 
Fairy light x2
Axes (?)
Batteries
Arduino


BOX : 

Based on : https://github.com/openfab-lab/openfab/blob/master/Missions/maker-library.md
600x400 mm with plywood on the sides (people can walk on it, dance, whatever without breaking the mecanism)

NOT PARAMETRIC YET ! don't remember how to do it...

**Comment by zuperninja** [comment]
Issue 
Grass ? how to dig hole and give back the land ok

**Comment by zuperninja** [comment]
vérifier angle de coupe
code pour montage
drill à 4cm du bord

**Comment by zuperninja** [comment]
Soucis avec le modèle fait sur fusion360 pour les angles. Décalage entre angle déjà coupé dans le bois qui parait bien et l'angle dans fusion 360 qui ne correspond pas. 
Next step : refaire un schéma, apprendre les maths, et refaire le modèle 3D

**Comment by zuperninja** [comment]
Samedi 23 décembre : process + test boulon joint + préparation bois : 2h
Jeudi 28 décembre : prototype lvlTOP : 2h
Vendredi 29 décembre : prototype lvlTop + angle lvl4 : 2h

**Comment by zuperninja** [comment]
Liste à acheter : 

https://lite.framacalc.org/mAV8gqQ0j6

**Comment by zuperninja** [comment]
TO DO : 

- [ ] prototype before the 5th
- [ ] find chicken wire and material to start building when we have the size of the head
- [ ] 3D model of the stage
- [ ] arduino circuit
- [ ] 3D model of the eye + prototype
- [ ] decor scenery schema

**Comment by zuperninja** [comment]
Arduino + servo motor : 
http://www.inmoov.fr/wp-content/uploads/2015/02/Introduction-to-Servo-Motors-Arduino.pdf
http://i.stack.imgur.com/CEFam.png

**Comment by zuperninja** [comment]
ROOCKY MISTAKE ! WARNING

Put the nuts before bending the bold !

**Comment by zuperninja** [comment]
![image](https://user-images.githubusercontent.com/25099826/34482291-9a72aa58-efe9-11e7-890d-ef16bbae6743.png)

**Comment by nicolasdb** [comment]
https://www.treehugger.com/modular-design/zomes-recycled-wood-balanced-carpentry.html

https://simplydifferently.org/Zome

Attention pour plus tard, quand on en a discuté avec Marc à l'époque, il y a un nombre pair et impair de structure, une qui apaise, une qui excite. Donc attention à l'objectif du zome, si c'est pour ta chambre par exemple...

**Comment by zuperninja** [comment]
C'est un nombre impair. Tu te souviens du quel est le quel ? C'est pour un festival de musique :) les deux marcheront au pire :D

**Comment by nicolasdb** [comment]
non, me souvient plus

**Comment by zuperninja** [comment]
<img width="774" alt="stage_disposition" src="https://user-images.githubusercontent.com/25099826/34564586-ca258698-f189-11e7-8e5f-e3b727ff25cb.PNG">

**Comment by zuperninja** [comment]
[zomelist.pdf](https://github.com/zuperninja/blog/files/1603394/zomelist.pdf)

**Comment by zuperninja** [comment]
These are video of the 3D models we did during the process : 
https://youtu.be/T3YPdE6htk8 
https://youtu.be/gn_qoHTbwDI

**Comment by zuperninja** [comment]
## Stage + Shade Area

Frame Wood  
Big main zome (beam dimension = 2cm x 3.5cm x 1m ) = 24 m of 15cm wide x 3.5 cm thick pine.
Medium zome = 12 m of 15 cm wide x 3.5cm thick pine NOTE There are 2 mediums so total 24 m of wood)
Smaller zome = 4 m of 15 m wide x 3.5 cm thick pine
Extra = 6 m 15 cm x 3.5 for fuck ups and unthought of stuff
DJ Table Wood Frame =  14 m of 6 cm x 4 cm pine
Bamboo = 20 2m lengths (bamboo is normally more than 4 m long so maybe 10 pieces)
Pallets for stage platform = 7 pallets
Ply Wood (dj top) = 1 piece 2 cm thick
Bolts = 324 
Nuts = 648
Washer = 648
Screws = 400
Paint = 2 small buckets of white.
Fabric 
Big main Zome = 35 m squared
Medium Zome = 18 m squared NOTE there are 2 Medium Domes so total fabric ( 35 m squared)
Small Zome = 12 m squares
Rope = 15 m

## Eye + ears :

Wood : 500x30x30mm = 25pc (any kind)
Plywood : 500x500mm = 10pc (can use scrap)
Servomotor + arduino (i will buy it in vietnam)
Wire (already have)
Pipe cleaner (already have)
Chicken wire (i don't know how much i need yet. Leftover / can be share)
Newspaper (leftover / can be share)
Paste for papier maché (leftover / can be share)
Paint : primary color + black and white (leftover / can be share)
Clear spray vernish (leftover / can be share)
Extension plug x1
Electrical wire
LED strips (if we already have some, not sure yet)
Fabric : scrap + 18meter blue/green/silver for the mask of the giant + fake fur for the eyebrow ??? (i can take care of that)

## Tools

Drill
Staplers
Hammer, 
jiggsaw (for the platform), 
nail gun (platform too, or drill)
Ladders x 2 or 3
Power Extension cord

## Fun Stuff

Lights
Bubble Machine
A fan for if it's too hot under the zome for the dj

**Comment by zuperninja** [comment]
fritzing
https://github.com/e-radionicacom/e-radionica.com-Fritzing-Library-parts-
https://github.com/adafruit/Fritzing-Library

**Comment by zuperninja** [comment]
https://learn.adafruit.com/16-channel-pwm-servo-driver?view=all

**Comment by zuperninja** [comment]
A part allumer des LED sur arduino, je sais pas comment l'électricité marche. Grosse partie d'apprentissage. Josh me conseille d'utiliser l'interface servo motor d'Arduino. Dessus j'y trouve toute les explications que je schématise sur Fritzing. 
J'ai quand même peur de passer à la pratique et de tout faire cramer. Car j'aurai pas le temps de retourner au vietnam ou à bangkok pour racheter des composants.... Je continue du coup de bien checker tout et schématiser sur fritzing

**Comment by zuperninja** [comment]
http://www.cmflying.com/index.php?name=product&file=readproduct&id=81

**Comment by nicolasdb** [comment]
Tu veux faire quoi au juste en électricité?

**Comment by zuperninja** [comment]
Faire des yeux en animatronique. J'ai eu une discussion dessus avec Mickael (electro guy). Ca avance, j'aurai surement besoin d'un avis pour le mécanisme par contre :D

**Comment by zuperninja** [comment]
http://eskimon.fr/287-arduino-602-un-moteur-qui-de-la-tete-le-servo-moteur

**Comment by nicolasdb** [comment]
Damn girl, 
![image](https://user-images.githubusercontent.com/12049360/35442933-686e0a2a-02a9-11e8-8d68-00bd62545866.png)

**Comment by zuperninja** [comment]
http://tiptopboards.free.fr/arduino_forum/viewtopic.php?f=2&t=24

**Comment by zuperninja** [comment]
@nicolasdb : je sais surtout pas ce que je fais... mais je commence à comprendre

cadeau : une photo de l'avancée du graaand zome 

![image](https://user-images.githubusercontent.com/25099826/35443306-37ba9a0e-02dd-11e8-861b-0e51a5b35260.png)

**Comment by nicolasdb** [comment]
ben, c'est du super bouleau :)

trop bien.

**Comment by zuperninja** [comment]
![image](https://user-images.githubusercontent.com/25099826/35472004-86236ede-0399-11e8-9e5c-e8c8bc386871.png)
![image](https://user-images.githubusercontent.com/25099826/35472006-8ca2e0c8-0399-11e8-93c2-844b35657687.png)
![image](https://user-images.githubusercontent.com/25099826/35472007-91f5c22a-0399-11e8-9cd1-558cdefe3326.png)
Voilà les avancées du jour. Le 4eme level (violet) s'affaisse bcp. Les clous (trop mous de thailande) se defont et le bois se déforme (humidité+trop de noeuds)
Certains tissus se cassent la gueule (la meilleure technique c'est masking tape + agrafes).

demain on essaye de réenforcer les violets (ce qu'on aurait du faire depuis le début)

Mais bon, ça tient, ca supportera juste pas les gens qui tapent dedans.

on étai 8 à le porter + 2 qui mettent les boulons

**Comment by zuperninja** [comment]
1 programme automatique avec blinking et mouvement de l'oeil lent

1 programme pour télécommande (joystick haut/bas + joystick droite/gauche) + bouton ouverture fermeture paupière

**Comment by zuperninja** [comment]
Du tissu pour le 2eme niveau qui ressemble à rien
oeillet
corde

**Comment by zuperninja** [comment]
3 servo TowerPro SG-5010 qui demande chacun 1Ampère. Reliés au receiver de la télécommande.

Pas assez de courant (ampère de 550mA au lieu de 3A).

J'ai un boitier comme ça. Je vais essayer de le brancher avec une prise secteur (3 fiches) et en output une breadboard avec résistance 330ohm et une LED. Pour voir si c'est bien branché, car j'ai pas de multimètre. 
![image](https://user-images.githubusercontent.com/25099826/35567341-52eb7862-05f7-11e8-8ce9-493091b421bb.png)

Après, il faut que je répartisse le courant entre les 3servos (en série ?) ainsi que le petit ventilateur et les lumières.

**Comment by zuperninja** [comment]
![image](https://www.facebook.com/eatingoutmaps/photos/a.328984457526488.1073741829.327831290975138/383632772061656/?type=3&theater)

![image](https://user-images.githubusercontent.com/25099826/36654738-2d4cbeb8-1af1-11e8-9a6d-9f988f64be1b.png)

**Comment by nicolasdb** [comment]
Quand on est sur ton site, on ne voit pas tout ce que tu as fais comme ici. 
Je propose un truc: 
Tu ajoute un lien vers cette issue de la page post, et un lien vers le post à partir de l'issue dans le premier com. 
Et puis tu clos ton issue, quand le job est cloturé ET posté. (ce qui n’empêche pas de la rouvrir au cas où)
ça donne un bon feeling de "voilà ça, c'est fait"
