### ISSUE TITLE
Boite de rangement inkscape laser cut

### ISSUE THREAD

**Issue by zuperninja** [zuperninja/zuperninja.github.io#22]
Configuration du pluggin inkscape pour lasersaur

<img width="248" alt="box" src="https://user-images.githubusercontent.com/25099826/42323253-ca905de6-805f-11e8-8ce6-8cfeaeb79abc.PNG">

**Comment by zuperninja** [comment]
Basé sur  

https://nicolasdb.github.io/post/boxes/
https://nicolasdb.github.io/post/lasermdf3/

**Comment by zuperninja** [comment]
Explication laser:

Si mon matériau fait 12 mm, je dois régler la focale au centre de cette matière. Soit ici 6mm.
15mm - 6mm = 9mm entre la lentille est la matière
15mm = est la focale de cette lentille.

![image](https://user-images.githubusercontent.com/25099826/42446073-5d6a3d5e-8375-11e8-826a-827ca2bd4a15.png)
![image](https://user-images.githubusercontent.com/25099826/42446096-69978b40-8375-11e8-9015-1dd76f4d45e8.png)

**Comment by nicolasdb** [comment]
Attention, 15mm n'est pas la focale. Mais l'écart entre le point de focale et le bas du porte lentille. 
La distance de focale de cette lentille est de 76mm. Le haut du cône dans le dessin.

**Comment by nicolasdb** [comment]
whophophop, c'est où que t'as ajouté ces infos au final. 
C'est chouette ces vues. 

Et Dewi me l'a encore demandé, c'était tjs pas clair. Le brol sur le dessin, c'est bien le matériaux, pas la table/honeycomb, la table n'a absolument rien à voir dans ce calcul.  Faudra réinsister dans le tuto.
Et Michiko aussi, y a 2 jours, parce que Dewi n'était pas certain de la logique quand il lui a fait l'intro.

**Comment by zuperninja** [comment]
Je le mets de coté pour ma prochaine fois à openfab, me souviens plus, ça m'énerve alors je l'enfouies :)
